name: traxxas_app
description: "Android application for RC car command."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  quick_blue: 
    path: 'quick_blue'                  # for BLE communications
  flutter_joystick: ^0.0.4              # for joystick use
  http: ^1.1.0                          # for http protocol
  shared_preferences: ^2.2.0            # .???
  permission_handler: '>=9.0.0 <15.0.0' # .???
  convert: ^3.0.0                       # .???
  logging: ^1.0.2
  web_socket_channel: ^3.0.0
  video_player: ^2.2.12
  chewie: ^1.2.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
